server:
  port: 8080
spring:
  application:
    name: finance-control
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
